In [4]:
import numpy as np
import pandas as pd

In [5]:
df= pd.read_csv('cars.csv')
df.sample(10)

        brand  km_driven    fuel         owner  selling_price
4333  Hyundai      56290  Diesel   First Owner         450000
5121   Maruti      35000  Petrol   First Owner         220000
7945   Toyota     250000  Diesel   First Owner         730000
3671   Maruti      30000  Petrol   First Owner         250999
7783  Hyundai     110000  Diesel  Second Owner         380000
1670   Maruti      80000  Diesel   First Owner         480000
1133    Volvo       2000  Diesel   First Owner        2475000
3071   Maruti      35000  Diesel   First Owner         830000
7855  Hyundai      74000  Diesel   First Owner         750000
443   Hyundai      93000  Petrol   First Owner         409999

In [6]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

**1. One Hot Encoding using Pandas**

In [ ]:
#Dummy Variable Trap
pd.get_dummies(df,columns=['owner','fuel'])

,brand,km_driven,selling_price,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
0,Maruti,145500,450000,True,False,False,False,False,False,True,False,False
1,Skoda,120000,370000,False,False,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,True,False,False
4,Maruti,120000,130000,True,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,True,False,False,False,False,False,False,False,True
8124,Hyundai,119000,135000,False,True,False,False,False,False,True,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,True,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,True,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,True,False,False

**2. K-1 One Hot Encoding OR N-1 One Hot Encoding**

In [8]:
#Get rid of one dummy variable to avoid Dummy Variable Trap
pd.get_dummies(df,columns=['owner','fuel'],drop_first=True)

,brand,km_driven,selling_price,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_Diesel,fuel_LPG,fuel_Petrol
0,Maruti,145500,450000,False,False,False,False,True,False,False
1,Skoda,120000,370000,False,True,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,True
3,Hyundai,127000,225000,False,False,False,False,True,False,False
4,Maruti,120000,130000,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,False,False,False,True
8124,Hyundai,119000,135000,True,False,False,False,True,False,False
8125,Maruti,120000,382000,False,False,False,False,True,False,False
8126,Tata,25000,290000,False,False,False,False,True,False,False
8127,Tata,25000,290000,False,False,False,False,True,False,False

**3. One Hot Encoding Using SkLearn**

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(df.drop('selling_price',axis=1),df['selling_price'],test_size=0.2,random_state=42)

In [10]:
X_train.head()

        brand  km_driven    fuel                 owner
6518     Tata       2560  Petrol           First Owner
6144    Honda      80000  Petrol          Second Owner
6381  Hyundai     150000  Diesel  Fourth & Above Owner
438    Maruti     120000  Diesel          Second Owner
5939   Maruti      25000  Petrol           First Owner

In [11]:
from sklearn.preprocessing import OneHotEncoder

In [13]:
ohe= OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [14]:
X_train_new= ohe.fit_transform(X_train[['owner','fuel']])
X_test_new= ohe.transform(X_test[['owner','fuel']])

In [15]:
X_train_new.shape

(6502, 7)

In [16]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Tata', 2560, 0, ..., 0, 0, 1],
       ['Honda', 80000, 0, ..., 0, 0, 1],
       ['Hyundai', 150000, 1, ..., 1, 0, 0],
       ...,
       ['Hyundai', 35000, 0, ..., 0, 0, 1],
       ['Maruti', 27000, 0, ..., 1, 0, 0],
       ['Maruti', 70000, 0, ..., 0, 0, 1]], dtype=object)

**4. One Hot Encoding with Top Categories**

In [17]:
counts=df['brand'].value_counts()

In [18]:
df['brand'].nunique()
threshold=100

In [19]:
repl=counts[counts<=threshold].index

In [20]:
pd.get_dummies(df['brand'].replace(repl,'uncommon')).sample(10)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
1360,False,False,False,False,False,False,False,False,False,False,True,False,False
4820,False,False,False,False,False,False,False,False,False,False,True,False,False
4811,False,False,False,False,False,False,True,False,False,False,False,False,False
1470,False,False,False,False,False,True,False,False,False,False,False,False,False
3060,False,False,False,False,True,False,False,False,False,False,False,False,False
328,False,False,False,False,False,False,True,False,False,False,False,False,False
1796,False,False,False,False,False,False,False,False,False,False,True,False,False
7220,False,False,False,False,False,False,True,False,False,False,False,False,False
5268,False,False,False,False,False,False,True,False,False,False,False,False,False
2806,False,False,False,False,False,False,True,False,False,False,False,False,False